[homelab]
proxy             ansible_host=192.168.100.10
streaming         ansible_host=192.168.100.11
arr               ansible_host=192.168.100.12
downloader        ansible_host=192.168.100.13
monitoring        ansible_host=192.168.100.14
library           ansible_host=192.168.100.15

[router]
router-vm         ansible_host=192.168.1.159

[pihole]
pihole-raspberry  ansible_host=192.168.1.225 ansible_user=arian
