[homelab]
proxy.homelab       ansible_host=192.168.100.10
streaming.homelab   ansible_host=192.168.100.11
arr.homelab         ansible_host=192.168.100.12
downloader.homelab  ansible_host=192.168.100.13
monitoring.homelab  ansible_host=192.168.100.14
library.homelab     ansible_host=192.168.100.15

[router]
router.homelab      ansible_host=192.168.1.159

[pihole]
pihole-raspberry    ansible_host=192.168.1.225 ansible_user=arian
