all:
  children:
    router:
      hosts:
        home-router:
          ansible_host: 192.168.1.159
    proxy:
      hosts:
        proxy-vm:
          ansible_host: 192.168.100.10
    streaming:
      hosts:
        streaming-vm:
          ansible_host: 192.168.100.11
    arr:
      hosts:
        arr-vm:
          ansible_host: 192.168.100.12
    downloader:
      hosts:
        downloader-vm:
          ansible_host: 192.168.100.13
    monitoring:
      hosts:
        monitoring-vm:
          ansible_host: 192.168.100.14
