all:
  children:
    proxy:
      hosts:
        proxy-vm:
          ansible_host: 192.168.1.10
    streaming:
      hosts:
        streaming-vm:
          ansible_host: 192.168.1.11
    arr:
      hosts:
        arr-vm:
          ansible_host: 192.168.1.12
    downloader:
      hosts:
        downloader-vm:
          ansible_host: 192.168.1.13
    paperless:
      hosts:
        paperless-vm:
          ansible_host: 192.168.1.14
    monitoring:
      hosts:
        monitoring-vm:
          ansible_host: 192.168.1.15
    rss:
      hosts:
        rss-vm:
          ansible_host: 192.168.1.16
