---
- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Deploy dnsmasq config
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/homelab.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart dnsmasq

- name: Enable and start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
